INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("01/11/1996","Cum sociis natoque penatibus et"," RECEBIDO","4.93");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("13/01/1992","arcu et pede."," RECEBIDO","7.54");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("16/03/1989","egestas. Aliquam"," RECEBIDO","1.35");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("19/11/2004","libero mauris,"," RECEBIDO","7.48");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("30/10/2013","Integer eu lacus. Quisque imperdiet,"," RECEBIDO","7.72");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("27/07/2006","auctor vitae, aliquet nec, imperdiet"," RECEBIDO","2.54");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("22/01/2013","augue ut lacus."," RECEBIDO","2.27");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("19/11/2000","dolor,"," RECEBIDO","5.86");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("09/07/1993","at, egestas a, scelerisque sed,","PENDENTE ","8.67");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("06/08/1993","viverra. Donec"," RECEBIDO","9.18");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("25/07/2008","malesuada vel, convallis in,","PENDENTE ","3.68");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("10/06/2006","ut, nulla. Cras eu"," RECEBIDO","8.79");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("09/07/2019","pede. Cras","PENDENTE ","5.29");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("27/09/2017","ultricies adipiscing, enim mi"," RECEBIDO","5.43");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("27/10/2006","nunc, ullamcorper eu, euismod","PENDENTE ","4.73");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("27/08/1993","in consequat enim diam vel"," RECEBIDO","3.43");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("02/06/2011","malesuada id, erat. Etiam vestibulum"," RECEBIDO","9.39");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("26/05/2018","risus. Nulla eget metus"," RECEBIDO","2.41");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("03/08/2016","at fringilla purus mauris a"," RECEBIDO","7.56");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("29/07/2010","tellus. Phasellus elit pede, malesuada","PENDENTE ","8.71");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("08/12/1990","ac"," RECEBIDO","9.45");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("16/05/2018","euismod enim. Etiam gravida molestie"," RECEBIDO","2.73");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("30/05/2014","neque venenatis lacus. Etiam"," RECEBIDO","1.02");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("28/10/1992","dapibus id, blandit","PENDENTE ","7.16");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("22/09/2010","Cras convallis"," RECEBIDO","3.37");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("12/10/2007","Aliquam"," RECEBIDO","8.96");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("18/11/2017","ultrices. Duis","PENDENTE ","1.74");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("21/01/1994","est arcu ac orci. Ut"," RECEBIDO","7.29");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("15/03/2017","sed, est."," RECEBIDO","9.50");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("18/10/1990","sit amet","PENDENTE ","8.70");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("11/10/2020","diam nunc,","PENDENTE ","0.63");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("22/09/1994","orci, consectetuer euismod","PENDENTE ","1.00");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("27/01/2019","sem, vitae","PENDENTE ","9.52");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("26/03/2018","ac, eleifend","PENDENTE ","1.43");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("04/04/1996","est ac mattis semper,","PENDENTE ","9.58");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("13/02/1997","natoque penatibus et","PENDENTE ","1.13");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("16/08/2011","nibh enim, gravida sit amet,"," RECEBIDO","3.12");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("13/02/2000","Donec non"," RECEBIDO","9.93");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("06/01/1991","ultricies adipiscing,"," RECEBIDO","6.50");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("20/11/2005","non"," RECEBIDO","1.20");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("29/11/1996","justo eu arcu. Morbi sit"," RECEBIDO","5.41");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("13/07/1992","neque pellentesque massa lobortis","PENDENTE ","8.95");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("15/09/1991","elementum purus, accumsan interdum","PENDENTE ","7.30");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("19/04/2001","mus. Proin vel nisl.","PENDENTE ","6.76");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("06/07/2008","diam. Duis mi enim, condimentum"," RECEBIDO","5.35");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("16/11/2014","nec quam. Curabitur vel"," RECEBIDO","7.74");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("01/07/1991","Ut sagittis"," RECEBIDO","4.00");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("26/04/2004","aliquet","PENDENTE ","6.68");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("08/12/2007","Phasellus elit pede,","PENDENTE ","2.53");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("28/08/2005","nec tellus. Nunc lectus pede,","PENDENTE ","0.00");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("19/09/2008","arcu vel quam dignissim pharetra."," RECEBIDO","1.19");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("16/06/2011","lectus pede, ultrices a,"," RECEBIDO","5.35");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("06/08/2004","Integer id magna et","PENDENTE ","4.56");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("24/10/2015","enim. Mauris quis","PENDENTE ","7.38");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("29/07/2019","a feugiat tellus lorem"," RECEBIDO","2.38");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("21/10/2019","vestibulum. Mauris magna. Duis","PENDENTE ","9.74");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("29/01/2007","lacus vestibulum lorem, sit","PENDENTE ","1.51");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("14/05/1993","Sed nunc est,","PENDENTE ","2.98");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("28/03/2012","consectetuer adipiscing elit.","PENDENTE ","0.13");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("22/04/2020","eu,"," RECEBIDO","9.32");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("18/03/1998","venenatis"," RECEBIDO","8.64");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("16/10/2012","molestie in,","PENDENTE ","0.00");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("15/10/1993","sem elit,","PENDENTE ","8.49");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("08/03/2004","Duis sit amet diam eu"," RECEBIDO","8.87");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("01/09/2004","Curae; Donec"," RECEBIDO","4.20");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("15/04/2020","ullamcorper. Duis cursus, diam at"," RECEBIDO","9.13");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("25/05/1996","eu, odio. Phasellus at augue"," RECEBIDO","7.55");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("15/11/2000","montes, nascetur ridiculus mus. Proin","PENDENTE ","0.23");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("22/10/2009","aliquet magna a neque."," RECEBIDO","6.69");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("09/03/2003","posuere","PENDENTE ","4.68");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("28/11/2002","lorem lorem,","PENDENTE ","7.65");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("20/11/2005","Nulla eget metus eu erat"," RECEBIDO","3.30");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("14/03/1999","dolor dapibus","PENDENTE ","0.48");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("23/04/2019","pede"," RECEBIDO","2.50");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("24/11/2003","In at pede."," RECEBIDO","3.23");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("13/05/2001","tincidunt nibh. Phasellus nulla.","PENDENTE ","9.51");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("07/12/1991","Cras lorem lorem, luctus ut,","PENDENTE ","8.93");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("20/11/1993","mollis vitae, posuere at,"," RECEBIDO","4.52");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("20/06/1992","dictum cursus. Nunc mauris elit,"," RECEBIDO","5.95");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("16/11/1998","semper pretium neque. Morbi","PENDENTE ","2.07");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("18/10/2014","dignissim. Maecenas ornare egestas ligula."," RECEBIDO","3.15");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("17/12/1992","tempus,","PENDENTE ","0.72");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("06/02/2015","lacus, varius"," RECEBIDO","6.28");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("06/04/2010","fermentum vel, mauris. Integer sem","PENDENTE ","4.54");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("05/04/2011","velit. Sed malesuada augue ut","PENDENTE ","7.78");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("01/09/2010","at"," RECEBIDO","5.18");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("13/07/1999","massa.","PENDENTE ","9.75");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("12/07/2014","natoque penatibus et magnis dis","PENDENTE ","2.02");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("11/09/2010","vitae"," RECEBIDO","9.05");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("15/10/1990","auctor","PENDENTE ","3.67");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("31/07/1995","mollis.","PENDENTE ","0.82");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("01/07/2006","Integer mollis. Integer tincidunt","PENDENTE ","9.45");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("01/09/2001","felis, adipiscing fringilla,"," RECEBIDO","1.49");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("06/03/1992","velit. Pellentesque ultricies"," RECEBIDO","6.85");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("06/05/2002","lectus convallis est, vitae","PENDENTE ","3.25");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("20/09/1997","Duis at lacus.","PENDENTE ","6.81");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("16/07/1999","mattis. Cras eget nisi dictum","PENDENTE ","3.33");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("25/04/1997","justo"," RECEBIDO","6.89");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("15/11/2018","elit."," RECEBIDO","6.07");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("19/03/2014","mauris sit amet lorem semper","PENDENTE ","9.32");