INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("05/03/2019","eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec,"," RECEBIDO","13.90");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("01/05/2020","netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed"," RECEBIDO","7.45");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("05/08/2020","a, arcu. Sed et libero.","PENDENTE ","84.64");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("07/12/2018","nulla. Donec non justo. Proin non massa non","PENDENTE ","89.79");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("30/05/2019","feugiat metus"," RECEBIDO","52.52");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("30/05/2020","a, magna. Lorem ipsum dolor sit amet,","PENDENTE ","98.57");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("20/11/2018","blandit. Nam nulla magna, malesuada vel, convallis in, cursus et,"," RECEBIDO","94.40");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("16/05/2020","magna nec quam. Curabitur vel"," RECEBIDO","9.31");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("21/08/2019","porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis","PENDENTE ","77.16");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("18/08/2020","blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer"," RECEBIDO","35.78");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("02/01/2020","venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus,","PENDENTE ","80.96");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("23/01/2019","Curabitur vel lectus. Cum","PENDENTE ","83.91");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("23/07/2020","vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae"," RECEBIDO","64.22");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("27/01/2020","sed libero. Proin sed turpis nec mauris blandit mattis.","PENDENTE ","23.90");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("27/02/2020","at, nisi. Cum sociis natoque penatibus et magnis dis parturient","PENDENTE ","40.01");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("15/10/2019","Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at"," RECEBIDO","76.46");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("18/04/2019","sit amet massa. Quisque porttitor eros","PENDENTE ","28.58");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("27/12/2018","Donec at arcu. Vestibulum ante ipsum primis in faucibus"," RECEBIDO","70.28");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("21/03/2019","aliquet, metus urna convallis erat, eget tincidunt dui augue"," RECEBIDO","37.09");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("22/02/2019","consectetuer mauris id sapien. Cras"," RECEBIDO","55.83");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("03/05/2020","libero et tristique pellentesque, tellus sem mollis dui,","PENDENTE ","67.14");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("22/04/2019","varius et, euismod et, commodo at, libero. Morbi accumsan laoreet"," RECEBIDO","97.93");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("04/11/2020","adipiscing fringilla,"," RECEBIDO","43.05");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("18/11/2018","gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras"," RECEBIDO","68.57");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("12/11/2019","accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis","PENDENTE ","88.54");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("15/11/2018","odio tristique"," RECEBIDO","16.29");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("15/06/2019","Proin vel arcu eu odio tristique pharetra. Quisque ac"," RECEBIDO","13.76");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("10/09/2019","ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo"," RECEBIDO","42.21");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("14/08/2020","in sodales elit erat"," RECEBIDO","87.76");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("22/01/2020","quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas."," RECEBIDO","12.03");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("25/12/2019","mauris ipsum porta elit, a feugiat tellus lorem eu metus.","PENDENTE ","14.79");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("28/08/2019","fringilla. Donec feugiat metus sit"," RECEBIDO","61.30");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("06/10/2020","Nulla facilisi. Sed neque. Sed eget lacus. Mauris","PENDENTE ","8.46");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("10/10/2019","nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante."," RECEBIDO","25.91");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("25/09/2020","lobortis quam a felis ullamcorper viverra. Maecenas iaculis"," RECEBIDO","68.24");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("12/02/2020","pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi.","PENDENTE ","42.60");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("19/05/2019","sapien. Aenean massa. Integer vitae nibh. Donec est mauris,","PENDENTE ","49.01");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("19/12/2018","Quisque varius. Nam porttitor scelerisque neque.","PENDENTE ","39.99");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("07/02/2019","tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non"," RECEBIDO","42.37");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("30/12/2018","dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque,","PENDENTE ","53.18");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("01/01/2019","ante. Nunc"," RECEBIDO","92.16");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("17/02/2020","consectetuer adipiscing elit. Curabitur","PENDENTE ","97.71");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("04/06/2020","sed tortor. Integer aliquam"," RECEBIDO","42.10");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("17/02/2019","urna convallis","PENDENTE ","84.93");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("13/06/2019","ante lectus","PENDENTE ","34.65");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("17/01/2019","enim diam vel arcu. Curabitur"," RECEBIDO","41.30");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("26/09/2019","eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec","PENDENTE ","15.70");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("15/01/2020","ipsum ac mi eleifend"," RECEBIDO","21.53");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("13/06/2019","libero lacus, varius et, euismod et, commodo at, libero. Morbi"," RECEBIDO","96.56");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("03/08/2019","dignissim tempor arcu. Vestibulum ut eros","PENDENTE ","43.95");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("17/06/2019","Donec nibh. Quisque nonummy ipsum"," RECEBIDO","5.16");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("09/06/2019","Donec sollicitudin adipiscing ligula. Aenean"," RECEBIDO","69.27");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("12/10/2019","iaculis, lacus pede sagittis augue, eu tempor erat neque non quam."," RECEBIDO","49.44");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("07/10/2019","in felis. Nulla tempor augue ac ipsum. Phasellus vitae","PENDENTE ","32.45");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("01/09/2019","tempor lorem,","PENDENTE ","27.45");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("26/08/2019","sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare,","PENDENTE ","44.64");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("22/08/2019","rutrum eu, ultrices sit amet, risus. Donec"," RECEBIDO","76.88");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("08/02/2020","molestie","PENDENTE ","22.31");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("07/05/2019","hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In","PENDENTE ","41.08");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("23/02/2019","adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim nisl elementum purus, accumsan"," RECEBIDO","24.32");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("30/05/2019","sociosqu ad litora torquent per conubia nostra,","PENDENTE ","2.16");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("20/01/2019","Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum","PENDENTE ","83.82");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("17/08/2019","scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus","PENDENTE ","79.03");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("10/10/2020","Nunc","PENDENTE ","74.11");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("11/01/2020","luctus aliquet odio. Etiam"," RECEBIDO","64.30");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("03/07/2019","ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus"," RECEBIDO","58.01");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("28/01/2019","Nam porttitor"," RECEBIDO","66.52");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("03/09/2020","sit amet, consectetuer","PENDENTE ","43.23");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("15/07/2020","tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae"," RECEBIDO","49.86");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("27/03/2019","ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus","PENDENTE ","67.34");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("18/11/2019","porta elit, a feugiat tellus lorem","PENDENTE ","9.20");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("17/10/2020","mus. Donec dignissim magna a tortor. Nunc commodo"," RECEBIDO","63.08");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("06/02/2020","Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur","PENDENTE ","82.52");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("14/02/2019","adipiscing, enim mi tempor","PENDENTE ","72.90");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("04/06/2020","Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus."," RECEBIDO","49.28");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("10/06/2019","interdum ligula eu enim."," RECEBIDO","6.40");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("30/01/2020","in sodales elit erat vitae risus. Duis a mi fringilla mi"," RECEBIDO","22.80");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("01/04/2020","penatibus","PENDENTE ","23.98");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("24/11/2018","risus. Quisque libero lacus, varius et,","PENDENTE ","10.06");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("10/08/2019","enim nisl elementum purus, accumsan interdum libero dui nec"," RECEBIDO","87.16");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("05/12/2019","Fusce aliquet magna a neque. Nullam","PENDENTE ","32.13");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("25/02/2019","nec, leo. Morbi neque"," RECEBIDO","78.42");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("24/05/2020","metus. In nec orci. Donec nibh. Quisque nonummy ipsum non"," RECEBIDO","61.16");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("08/11/2020","mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec,"," RECEBIDO","21.14");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("19/11/2019","molestie pharetra nibh. Aliquam ornare, libero"," RECEBIDO","89.80");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("17/12/2018","lacinia. Sed congue, elit"," RECEBIDO","75.07");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("16/02/2020","consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus."," RECEBIDO","33.46");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("16/07/2020","Donec consectetuer mauris id sapien. Cras dolor dolor,"," RECEBIDO","44.46");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("13/11/2019","elit, pellentesque a, facilisis","PENDENTE ","13.81");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("14/05/2020","In lorem. Donec elementum, lorem ut aliquam iaculis, lacus","PENDENTE ","58.36");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("24/04/2020","Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus.","PENDENTE ","90.35");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("15/09/2020","Quisque","PENDENTE ","32.21");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("01/05/2020","parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam","PENDENTE ","64.73");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("17/08/2019","sollicitudin commodo","PENDENTE ","15.98");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("20/05/2020","Vivamus molestie dapibus ligula. Aliquam erat volutpat."," RECEBIDO","80.71");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("02/07/2019","hendrerit id, ante. Nunc mauris sapien, cursus in,","PENDENTE ","17.88");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("22/09/2019","varius orci, in consequat enim diam vel","PENDENTE ","87.57");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("10/12/2018","Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis","PENDENTE ","38.98");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("23/03/2020","Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque","PENDENTE ","25.64");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("29/03/2019","nisi a odio"," RECEBIDO","85.61");