INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("1996-12-02","Emprestimo Eduardo","RECEBIDO","40.93");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("1995-02-12","Emprestimo João","RECEBIDO","72.54");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("1998-01-15","Emprestimo Carlos","RECEBIDO","13.35");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("1993-12-17","Emprestimo Marcos","RECEBIDO","76.48");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("1999-10-28","Emprestimo Thiago","RECEBIDO","41.72");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("1998-08-22","Emprestimo Renato","RECEBIDO","29.54");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("2001-11-25","Emprestimo Lucas","RECEBIDO","24.27");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("2010-10-12","Emprestimo Paulo","RECEBIDO","52.86");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("2013-02-18","Emprestimo Bruno","PENDENTE ","86.67");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("2018-12-21","Emprestimo Luiz","RECEBIDO","91.18");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("2019-09-30","Emprestimo Pedro","PENDENTE ","39.68");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("2011-10-28","Emprestimo Guilherme","RECEBIDO","85.79");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("2015-03-25","Emprestimo Gustavo","PENDENTE ","52.29");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("2010-08-11","Emprestimo Felipe","RECEBIDO","59.43");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("2019-09-09","Emprestimo Ricardo","PENDENTE ","45.73");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("2018-01-14","Emprestimo Alessandro","RECEBIDO","32.43");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("2014-04-15","Emprestimo Danilo","RECEBIDO","97.39");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("2011-02-19","Emprestimo Saulo","RECEBIDO","28.41");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("1999-11-29","Emprestimo Willian","RECEBIDO","71.56");
INSERT INTO titulo (data_vencimento,descricao,status,valor) VALUES ("2013-12-20","Emprestimo Jonas","PENDENTE ","88.71");